name: Format Markdown files

on:
  pull_request:
    branches: 
      - main
    paths: 
      - '**/*.md'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify Markdown
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write **/*.md
          only_changed: True